[metadata]
name = dummy_robot_bridge
version = 0.1.0
author = You
license = Apache-2.0
description = Dummy Robot ROS2 Bridge (fibre integrated)

[options]
packages = find:
install_requires =

[options.entry_points]
console_scripts =
    discover_node.py = scripts.discover_node:main
    dummy_node.py = scripts.dummy_node:main
